# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
