# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbalert_django', '0002_searchphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='search_phrases',
            field=models.ManyToManyField(to='carbalert_django.SearchPhrase'),
        ),
    ]
